# Generated by Django 2.2.4 on 2019-08-31 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriveesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dater', models.DateField()),
                ('paysr', models.CharField(max_length=20)),
                ('viller', models.CharField(max_length=30)),
                ('numr', models.CharField(max_length=30)),
                ('noctr', models.BooleanField(max_length=30)),
                ('numc', models.CharField(max_length=30)),
                ('quintc', models.BooleanField(max_length=30)),
                ('nomc', models.CharField(max_length=30)),
                ('prixc', models.CharField(max_length=30)),
                ('nbptsc', models.CharField(max_length=30)),
                ('typec', models.CharField(max_length=30)),
                ('distc', models.CharField(max_length=30)),
                ('hdepc', models.CharField(max_length=30)),
                ('arv1c', models.CharField(max_length=30)),
                ('arv2c', models.CharField(max_length=30)),
                ('arv3c', models.CharField(max_length=30)),
                ('arv4c', models.CharField(max_length=30)),
                ('arv5c', models.CharField(max_length=30)),
                ('rapms4c', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('slug', models.SlugField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
        ),
    ]
