# Generated by Django 2.2.4 on 2019-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='arv1c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='arv2c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='arv3c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='arv4c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='arv5c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='dater',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='distc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='nbptsc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='numc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='numr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='paysr',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='prixc',
            field=models.IntegerField(),
        ),
    ]
