# Generated by Django 2.2.4 on 2019-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0002_auto_20190901_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='hdepc',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='noctr',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='quintc',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='rapms4c',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
