# Generated by Django 2.2.4 on 2019-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0003_auto_20190901_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriveesc',
            name='Hippor',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='arriveesc',
            name='exaquoarvc',
            field=models.BooleanField(default=False),
        ),
    ]
