# Generated by Django 2.2.4 on 2019-09-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0005_auto_20190901_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='arv5c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='nomc',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
