# Generated by Django 2.2.4 on 2019-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0006_auto_20190901_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='Hippor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
