# Generated by Django 2.2.4 on 2019-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0007_auto_20190901_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='Hippor',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
