# Generated by Django 2.2.4 on 2019-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0009_auto_20190901_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='hdepc',
            field=models.CharField(max_length=5, verbose_name='mm:ss'),
        ),
    ]
