# Generated by Django 2.2.4 on 2019-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0010_auto_20190901_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriveesc',
            name='hdepc',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='arriveesc',
            name='nomc',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
