# Generated by Django 2.2.4 on 2019-09-03 03:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0014_artileocr1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorieocr1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Articleocr1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('categorieocr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesa.Categorieocr1')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
