# Generated by Django 2.2.4 on 2019-09-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0015_articleocr1_categorieocr1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleocr1',
            old_name='categorieocr1',
            new_name='categorie',
        ),
    ]
