# Generated by Django 2.2.4 on 2019-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0017_partants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partants',
            old_name='commentac',
            new_name='commentapc',
        ),
        migrations.AlterField(
            model_name='partants',
            name='coteapr',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partants',
            name='coteavt',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partants',
            name='nomch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='partants',
            name='redkm',
            field=models.CharField(max_length=30),
        ),
    ]
