# Generated by Django 2.2.4 on 2019-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0018_auto_20190928_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partants',
            name='coteapr',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partants',
            name='coteavt',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
