# Generated by Django 2.2.4 on 2019-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0019_auto_20190928_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='partants',
            name='datec',
            field=models.CharField(default='01/12/2019', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partants',
            name='numc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partants',
            name='numr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partants',
            name='particular',
            field=models.CharField(default='ras', max_length=30),
            preserve_default=False,
        ),
    ]
