# Generated by Django 2.2.4 on 2019-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0020_auto_20191001_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='partants',
            name='motifrg',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
