# Generated by Django 2.2.4 on 2019-10-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0021_partants_motifrg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partants',
            name='particular',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
