# Generated by Django 2.2.4 on 2019-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0022_auto_20191005_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partants',
            name='redkm',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
