# Generated by Django 2.2.4 on 2019-10-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0023_auto_20191005_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partants',
            old_name='particular',
            new_name='particular1',
        ),
        migrations.AddField(
            model_name='partants',
            name='particular2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partants',
            name='rang',
            field=models.CharField(max_length=10),
        ),
    ]
