# Generated by Django 2.2.4 on 2019-10-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesa', '0024_auto_20191005_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partants',
            name='motifrg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partants',
            name='particular1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partants',
            name='particular2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partants',
            name='rang',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partants',
            name='redkm',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
